## KARMA SETTINGS
KARMA_MINIMUM = 10
KARMA_DEFAULT = 100
KARMA_MAXIMUM = 200
BONUS_TIME = 0.2
KARMA_TO_JOIN = 50

## CLONES DETECTION
## IP_HEADER is the META header that contains the IP
IP_HEADER = 'HTTP_X_FORWARDED_FOR' 